// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/graduate/dashboard": {
    params: {};
  };
  "/student/dashboard": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/account/logout" | "/account/signup" | "/graduate/dashboard" | "/student/dashboard" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./graduate/dashboard/page.jsx": {
    id: "graduate/dashboard/page";
    page: "/graduate/dashboard";
  };
  "./student/dashboard/page.jsx": {
    id: "student/dashboard/page";
    page: "/student/dashboard";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};